FESI-FlowIt/Frontend

- .github/workflows/storybook-cd.yml
- package-lock.json
- package.json
- src/stories/Example.stories.tsx
* [바로가기](https://www.chromatic.com/build?appId=686dd0f351950488ea229382&number=3)
---
* Closes #6 
---
**작업 개요**
- pr 올렸을 때 storybook을 자동으로 chromatic에 배포해주는 워크플로우
**주요 변경사항**
- storybook-cd.yml 워크플로우 제작
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [Feat/#6] Storybook 자동 배포 CD

- next.config.ts
- [바로가기]()
---
- Closes #32 
---
**작업 개요**
Next.js 프로젝트에서 SVG 파일을 React 컴포넌트로 사용할 수 있도록 SVGR 설정을 구성했습니다. 기존에 발생하던 "Element type is invalid" 오류를 해결하여 SVG 아이콘을 React 컴포넌트로 import하여 사용할 수 있게 되었습니다.
**주요 변경사항**
- next.config.ts에 TurboPack 환경용 SVGR 설정 추가
**기술적 구현 사항**
```
experimental: {
turbo: {
rules: {
'*.svg': {
loaders: ['@svgr/webpack'],
as: '*.js',
},
},
},
}
```
---
**에러 스크린샷**
**기능 동작 영상**
**추가 참고 자료**
> Fix:#32 - add svgr configuration in next.config.ts file for turbopack

- next.config.ts
…ding plugin
이번 PR은  빌드 설정 변경에 해당하여 스토리북 링크가 없습니다.
---
- Closes #43 
---
**작업 개요**
Tailwind CSS 유틸리티 클래스로 색상과 같은 스타일을 쉽게 제어할 수 있도록 SVGR 설정을 추가했습니다. 
**주요 변경사항**
- next.config.js 파일에 @svgr/webpack 로더 설정을 추가했습니다
**기술적 구현 사항**
- SVGR의 svgoConfig 옵션 중 convertColors: { currentColor: true } 플러그인을 활성화했습니다.
---
**기능 동작 영상**
**추가 참고 자료**
> [Feat/#43] svgr 플러그인 추가

- src/components/auth/AuthModal.tsx
- src/components/auth/LoginForm.tsx
- src/components/auth/SignUpForm.tsx
- src/components/ui/Button.tsx
- src/components/ui/Modal.tsx
- src/lib/routes.ts
- src/stories/auth/AuthModal.stories.tsx
- [바로가기](https://686dd0f351950488ea229382-kuomopspyy.chromatic.com/)
---
- Closes #67 
---
**작업 개요**
- 로그인 & 회원가입 실패 모달 제작
- 제작한 모달 로그인 & 회원가입 폼에 연결
**주요 변경사항**
- AuthModal.tsx
- LoginForm.tsx
- SignUpForm.tsx
- Button.tsx
- Modal.tsx
---
**스크린샷**
> [Feat/#67] 로그인 & 회원가입 실패 모달 제작

- src/api/apiWrapper.ts
- src/api/authApi.ts
- Closes #143 
---
**작업 개요**
- AccessToken 받는 로직을 수정한다.
**주요 변경사항**
- apiWrapper.ts
- accessToken 저장 로직 추가
- authApi.ts
- login api에서 accessToken 저장하는 로직 제거
---
> [Refactor:#143] - accessToken logic 수정

- src/components/auth/LoginForm.tsx
- src/components/auth/SignUpForm.tsx
- src/components/ui/CustomLoading.tsx
- src/stories/ui/CustomLoading.stories.tsx
- src/styles/globals.css
- [바로가기](https://686dd0f351950488ea229382-dkjnljxjwl.chromatic.com/)
---
- Closes #106 
---
**작업 개요**
- 로그인 & 회원가입 버튼 클릭 시 api 요청이 완료될 때까지 로딩 ui 보여주기
- 커스텀 로딩 ui 제작
**주요 변경사항**
- LoginForm.tsx
- SignUpForm.tsx
- CustomLoading.tsx
- CustomLoading.stories.tsx
- global.css
---
> [Refactor/#106] 로그인 & 회원가입 페이지에 loading ui 적용

- src/interfaces/goal.ts
- src/interfaces/todo.ts
- src/lib/goalMapper.ts
- src/lib/todoMapper.ts
- Closes #111 
---
**작업 개요**
백엔드 API와 프론트엔드 간의 데이터 연동을 위한 목표/할일 mapper를 구현
**주요 변경사항**
- 목표 Mapper 구현
- 할일 Mapper 구현
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [Feat/#111] 목표/ 할일 mapper 구현

- src/api/sidebarApi.ts
- src/app/(main)/dashboard/page.tsx
- src/components/goals/goalList/GoalsHeader.tsx
- src/hooks/useGoalCalendar.ts
- src/hooks/useGoals.ts
- src/hooks/useSidebar.ts
- Closes #166 
---
**작업 개요**
시연 전 예상하지 못한 동작을 해결합니다.
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [Refactor/#166] 시연 전 리팩토링

- src/api/apiWrapper.ts
- src/api/authApi.ts
- src/api/refreshAccessToken.ts
- src/app/api/logout/route.ts
- Closes #202 
---
**작업 개요**
- access & refresh token을 응답 바디로 받아 서버 쿠키로 저장
**주요 변경사항**
- apiWrapper.ts
- authApi.ts
- refreshAccessToken.ts
---
> [Fix/#202] 인증/인가 로직 수정

- src/stories/goals/GoalListDashboardCard.stories.tsx
- [바로가기]()
---
- Closes #205 
---
**작업 개요**
- No QueryClient set 오류 발생하던 문제 해결
- storybook 데코레이터에 QueryClientProvider 
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [fix/#205] 대시보드 목표별 할일 스토리북 오류 수정

- src/api/authApi.ts
- src/app/oauth/callback/page.tsx
- src/components/auth/SocialLoginCard.tsx
- src/hooks/auth/useSocialLogin.ts
- src/middleware.ts
- Closes #183 
---
**작업 개요**
- 카카오 소셜 로그인 기능 구현
**주요 변경사항**
- 카카오 소셜 로그인 버튼에 카카오 로그인 url 연결
- 소셜 로그인 api 제작 및 커스텀 훅 제작
- 소셜 로그인 콜백 페이지 제작
- 미들웨어에 소셜 로그인 router 반영
---
> [Feat/#183] 카카오 소셜 로그인 연결

- src/components/goals/calendar/CalendarDropdown.tsx
- src/components/goals/goalDetail/GoalDetailClient.tsx
- src/components/goals/goalDetail/GoalDetailHeader.tsx
- src/components/goals/goalList/GoalCard.tsx
- src/components/goals/goalList/GoalsFilterControls.tsx
- src/components/goals/goalList/GoalsList.tsx
- src/components/goals/goalList/GoalsPagination.tsx
- src/components/notes/NoteToolbar.tsx
- src/components/notes/NoteWriteClient.tsx
- Closes #262 
---
**작업 개요**
전체 UI의 반응형 개선 및 주요 컴포넌트의 레이아웃 최적화
**주요 변경사항**
- 목표 카드 그리드: 화면 크기 및 카드 잘림 여부에 따라 동적으로 컬럼 수 조정
- 노트 작성 툴바: 모바일/태블릿/데스크톱 환경별로 너비 및 위치 최적화
- 여러 컴포넌트(Todo, Note, Dropdown 등) 반응형 스타일 및 마진/패딩 조정
**기술적 구현 사항**
- ResizeObserver로 반응형 처리
---
**기능 동작 영상**
**추가 참고 자료**
> [Style/#262] 목표, 노트에 대한 반응형 수정

- src/api/refreshAccessToken.ts
- src/middleware.ts
- Closes #265 
---
**작업 개요**
- 토큰 갱신해주는 api 로직에서 데이터 형식을 다르게 받아서 형식 수정.
- 미들웨어에서 refreshToken 있을 때는 라우터 설정 x
---
> [Fix/#265] 토큰 갱신 에러 수정

- src/api/calendarApi.ts
- src/components/calendar/CalendarSection.tsx
- src/hooks/useGoalCalendar.ts
- Closes #278
---
**작업 개요**
- CalendarSection 컴포넌트에 에러 처리 추가
**주요 변경사항**
- 에러 상태에서 ErrorFallback 컴포넌트를 통한 일관된 에러 UI 제공
- HeatmapSection과 다르게 단일 API 호출이므로 별도 훅으로 분리하진 않음
---
|모바일|태블릿,데스크탑|
|--|--|
|<img width="554" height="602" alt="image" src="https://github.com/user-attachments/assets/82f8d468-ef5e-4491-8301-db21da6601cf" />|<img width="2851" height="1016" alt="image" src="https://github.com/user-attachments/assets/65ddf4b6-05c4-4cc3-ae26-27f140ce3cbd" />|
> [Feat/#278] 마감일 캘린더 에러 처리

- src/hooks/useGoals.ts
- src/hooks/useNotes.ts
- src/hooks/useTempNote.ts
- src/hooks/useTodos.ts
- Closes #267
---
**작업 개요**
전체적인 에러처리를 진행합니다.
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [FEAT/#267] 목표 할일 노트 에러 처리 (토스트)

- src/components/goals/GoalCardContent.tsx
- src/components/goals/GoalListDashboardCard.tsx
- [바로가기]()
---
- Closes #292 
---
**작업 개요**
- 마감일 00/00으로 수정
- 마감일 지나면 +로 되게 수정
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [Refactor/#292] 목표별 할일 대시보드 마감일 날짜 수정

- src/api/mapper/timerMapper.ts
- src/api/timerApi.ts
- src/components/timer/TimerControls.tsx
- src/interfaces/timer.ts
- [바로가기]()
---
- Closes #295 
---
**작업 개요**
- timer 시작시간과 종료시간 백엔드에 보내도록 수정
- 
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [Feat/#295] 타이머 종료 누르면 히트맵 업데이트 되게 수정

- src/components/goals/goalDetail/GoalDetailHeader.tsx
- src/components/goals/goalList/GoalCard.tsx
- src/components/todos/TodoAttachmentIcons.tsx
- src/components/todos/TodoModal.tsx
- src/styles/globals.css
- Closes #294
---
**작업 개요**
- 최종 발표 전 에러사항을 처리합니다.
**주요 변경사항**
- 다운로드 로직 변경
- d day 계산 변경
**기술적 구현 사항**
---
- 여기서 링크를 클릭하면
- 다음과 같이 이미지가 새 탭으로 뜨게됩니다
**기능 동작 영상**
**추가 참고 자료**
> [FIX/#294] 시연전 마지막 에러 수정

- src/components/timer/TimerWidget.tsx
- [바로가기]()
---
- Closes #301 
---
**작업 개요**
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [fix:/#301] 타이머 목표 조회 수정

- src/components/goals/GoalCardContent.tsx
- src/components/goals/GoalListDashboardCard.tsx
- [바로가기]()
---
- Closes #
---
**작업 개요**
**주요 변경사항**
**기술적 구현 사항**
---
**기능 동작 영상**
**추가 참고 자료**
> [Fix/#297] 마감일 오늘날짜 D-day로 나오게 수정
